apiVersion : v1
kind : Deployment
metadata : 
  name: qoentum-deployment
  labels:
    app: qoentum
  spec:
    replicas: 2
    selector: 
      matchlabels:
        app: qoentum
  template: 
    metadata:
      labels:
        app: qoentum
    spec: 
      containers: 
      - name: qoentum-dev
          image: iness22/qoentum:42
          ports: 
          - containerPort: 8083
      - name: database
          image: mysql:latest
          ports: 
          - containerPort: 3306
