apiVersion : apps/v1
kind : Deployment
metadata :
  name: qoentum
  labels:
    app: qoentum
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qoentum
  template:
    metadata:
      labels:
        app: qoentum
    spec:
      containers:
        - name: qoentum-dev
          image: iness22/qoentum:31
          ports:
            - containerPort: 8083
        - name: database
          image: mysql:latest
          ports:
            - containerPort: 3306
